### ISSUE TITLE
Integrate credo for credential operations

### ISSUE THREAD

**Issue by jrhender** [openwallet-foundation-labs/vc-api#20]
## Proposal
Integrate Credo for credential operations.
Link to repository: https://github.com/openwallet-foundation/agent-framework-javascript
Link to docs: https://credo.js.org/

### Support for data integrity signature
Credo [supports data integrity signatures](https://github.com/openwallet-foundation/agent-framework-javascript/tree/main/packages/core/src/modules/vc/data-integrity).
In particular, [Ed25519Signature2018](https://github.com/openwallet-foundation/agent-framework-javascript/blob/main/packages/core/src/modules/vc/data-integrity/signature-suites/ed25519/Ed25519Signature2018.ts) signatures seem to be supported out-of-the-box, which is the [main signature type used thus far within the VC API implementation](https://github.com/openwallet-foundation-labs/vc-api/blob/047f277b41818a953e2d6952974ec6562c565651/apps/vc-api/README.md?plain=1#L118).

### Support for JSON-LD VCs
The seems to be support for a document loader which could be used for adding contexts. https://github.com/openwallet-foundation/credo-ts/blob/main/packages/core/src/modules/vc/data-integrity/W3cJsonLdCredentialService.ts#L111

## Pros
- Using a project from within the Open Wallet Foundation would allow better synergy
- Would have a clearer path to supporting further VC technology such as SD-JWT and BBS signatures
- Ability to use custom JSON LD Contexts

## Cons
- If removing didKit, it could be a breaking change due to differing implementation details in proof issuance and/or verification

### Pre-implementation Research
- [x] decide if we should replace the existing credential operations library (didKit) or try to add Credo alongside
- [x] confirm whether or not additional LD contexts are supported by Credo (seems promising with document loader available)
- [x] check if/how Credo supports key creation/utilization at runtime
- [x] consider if it makes more sense to try to get VC API directly into Credo

### Implementation Steps
- [ ] replace didKit with credo. The [credential.service](https://github.com/openwallet-foundation-labs/vc-api/blob/develop/apps/vc-api/src/vc-api/credentials/credentials.service.ts#L13) is where didKit is currently integrated. I believe this is the core file that would need to be changed
- [ ] adjust documentation to explain why credo is now being used -> This should include the additional of an ADR
- [ ] adjust documentation to use context file links

**Comment by jrhender** [comment]
Completed by #38 . #39 opened to complete outstanding documentation fix.
